resolver: lts-5.17
packages:
- location: .
- location: 
    git: 'https://github.com/inq/bson.git'
    commit: '7b89a2886e31cd8dfe15109ae831d2902a31cb78'
- location:
    git: 'https://github.com/inq/mongodb.git'
    commit: 'bc25d6d749676e2e2c6077fbd8bc21eb91113965'
- location:
    git: 'https://github.com/inq/manicure.git'
    commit: '3c92de83ed3db9c536efaa47d5981f69cac3cdf6'
extra-deps: []
flags: {}
extra-package-dbs: []
