resolver: lts-7.1
packages:
- location: .
- location:
    git: 'https://github.com/inq/bson.git'
    commit: '0063a3481684556195a24c7c8d6d34b49d3af85c'
  extra-dep: true
- location:
    git: 'https://github.com/inq/mongodb.git'
    commit: 'bc25d6d749676e2e2c6077fbd8bc21eb91113965'
  extra-dep: true
- location: ./deps/manicure
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
