resolver: lts-7.14
packages:
- location: .
- location:
    git: 'https://github.com/inq/bson.git'
    commit: 'aef11b81bc658b894fddb5a6812a4dd204d275de'
  extra-dep: true
- location:
    git: 'https://github.com/inq/mongodb.git'
    commit: 'bc25d6d749676e2e2c6077fbd8bc21eb91113965'
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
